### ISSUE TITLE
Release management should not require specific url

### ISSUE THREAD

**Issue by lukewis** [Microsoft/vsts-node-api#118]
I encounted the same problem mentioned in #85.  It seems very odd that I need to specify different urls for different areas of the api.  For example, to access the "build" apis, I need to supply a url like this:

Access to build apis:
https://{mydomain}.visualstudio.com

However, to access RELEASE apis, I need to supply the following url:
https://{mydomain}.vsrm.visualstudio.com

Shouldn't the SDK handle this complexity for the user?

**Comment by bryanmacfarlane** [comment]
same issue as #131

**Comment by stephenmichaelf** [comment]
This will be resolved with #139 when it is reviewed/merged.

**Comment by stephenmichaelf** [comment]
@lukewis Could you get the latest 6.3.0-preview version and see if this works now?

**Comment by lukewis** [comment]
@stephenmichaelf Yep!  Working as expected in 6.3.0-preview.  Thanks!

**Comment by stephenmichaelf** [comment]
Thanks @lukewis!
