### ISSUE TITLE
Accounts API not available from npm release

### ISSUE THREAD

**Issue by DavidObando** [Microsoft/vsts-node-api#135]
I see that the repository includes file [AccountsApi.ts](https://github.com/Microsoft/vsts-node-api/blob/master/api/AccountsApi.ts) but it's not referenced from [WebApi.ts](https://github.com/Microsoft/vsts-node-api/blob/master/api/WebApi.ts). The package I get when I `npm install` the 6.x package therefore doesn't have support for accounts APIs, even though it's listed in the [readme](https://github.com/Microsoft/vsts-node-api/blob/master/README.md) as an available feature.

**Comment by stephenmichaelf** [comment]
Thanks @DavidObando I will add the AccountsApi to WebApi.

**Comment by stephenmichaelf** [comment]
@DavidObando This will be resolved by #139.

**Comment by stephenmichaelf** [comment]
@DavidObando Could you check the latest version and let me know if it works? It should expose the Accounts api through WebApi.ts.

npm install vso-node-api@preview

**Comment by stephenmichaelf** [comment]
Going to close as this should be resolved in the latest version. Please reopen if you have issues.
