### ISSUE TITLE
Identities API work around

### ISSUE THREAD

**Issue by jakekrammer-axosoft** [Microsoft/vsts-node-api#136]
I'm trying to find a way to get the authenticated user's information from VSTS using this package. After a user has authenticated in my app using their personal access token, what API call should I be using to get their display name and avatar?

My original guess was either the IdentitiesAPI's `getSelf()` or ProfileAPI's `getUserDefaults(includeAvatar=true)`, but both of those API's appear to be suffering from issue https://github.com/Microsoft/vsts-node-api/issues/131. 

An example of the errors I'm encountering: 
![screen shot 2018-01-30 at 9 46 34 am](https://user-images.githubusercontent.com/31415703/35586537-4c4cbd48-05b8-11e8-919b-1f0e10438cc8.png)

**Comment by bryanmacfarlane** [comment]
Yep.  We're on it.  Can you add to that issue so we can keep the info together?  Closing this one.

**Comment by bryanmacfarlane** [comment]
Also, adding a code snippet including the url you're using etc... to repro - just to make sure we validate you're exact scenario.
