### ISSUE TITLE
Issues with updating release metadata

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-node-api#144]
I'm trying to update one of the metadata fields on the release. In my release task I have the following code.

```
let serverUrl: string = task.getVariable("System.TeamFoundationCollectionUri");
let project: string = task.getVariable("System.TeamProject");
let releaseId: number = +task.getVariable("Release.ReleaseId");

let pat: string = task.getEndpointAuthorizationParameter("SYSTEMVSSCONNECTION", "AccessToken", false)
let authHandler = api.getPersonalAccessTokenHandler(pat);

let vsts: api.WebApi = new api.WebApi(serverUrl, authHandler);
let vstsRelease: IReleaseApi  = await vsts.getReleaseApi()

let metatdata: ReleaseUpdateMetadata = <ReleaseUpdateMetadata>{ keepForever: true }

let response: Release = await vstsRelease.updateReleaseResource(metatdata, project, releaseId)
```

Unfortunately no matter what I try, I do get the following error message:

`(node:3488) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to find api location for area: Release id: a166fde7-27ad-408e-ba75-703c2cc9d500`

Does anyone have an idea of what am I doing wrong or is it an issue of vsts-node-api module?

Thanks

**Comment by stephenmichaelf** [comment]
@mmajcica Could you try the latest version and let me know if it resolves this issue?

npm install vso-node-api@preview

We had an issue with DNS for some services that we recently resolved.

**Comment by mmajcica** [comment]
@stephenmichaelf that did the trick.

Thanks

**Comment by stephenmichaelf** [comment]
Thanks @mmajcica! Let us know if you run into any other issues.
