### ISSUE TITLE
Queueing a new build 

### ISSUE THREAD

**Issue by tgilgil** [Microsoft/vsts-node-api#147]
Hello,

I was implementing some simple automation for our chat bot and I couldn't figure out to trigger a _new_ build. 

The `BuildApi` has a function to queue an existing build but that is not what I'm looking for.
https://github.com/Microsoft/vsts-node-api/blob/master/api/BuildApi.ts#L701

The REST API has this endpoint
https://www.visualstudio.com/en-us/docs/integrate/api/build/builds#queue-a-build
(It requires a definition Id in the request's body)

Am I missing something or has it simply not been implemented?

Thanks 👍

**Comment by bryanmacfarlane** [comment]
I would recommend queuing a build in the UI and watching the wire with chrome, fiddler, charles.  Compare.  Our web UI uses all public rest apis so it's implemented :)

**Comment by tgilgil** [comment]
Thanks.

I misunderstood the API's signature. You can indeed pass in an empty object representing the `Build` instance with only the definition's `Id` specified.

```
const build = await buildApi.queueBuild({
    definition: {
        id: definitionId
    }
}, DEFAULT_PROJECT_ID);
```
