### ISSUE TITLE
Following the Get Started instructions doesn't work 

### ISSUE THREAD

**Issue by pabrams** [Microsoft/vsts-node-api#158]
1. created an empty folder in dos and moved into it.  I already have node v8.9.1 installed 
2. `npm init` - took defaults
3. `npm install vso-node-api --save`
4. create index.js
5. start adding code in sample under heading "Create a Connection" shown at https://github.com/Microsoft/vsts-node-api
6. In vscode, it doesn't like "string" because this is a .js file
7. Rename .js to .ts
8. In vscode, "Cannot find name 'require'"

If I replace 
`let vsts = require('vso-node-api');`
with 
`import * as vsts from 'vso-node-api';`
it's fine.

**Comment by bryanmacfarlane** [comment]
I think it's also missing the await in the getBuild factory call.

**Comment by omkar2607** [comment]
Hello..Did the create a connection work @pabrams ? I started following the same instructions. However I am unable to understand the steps for Running the .ts code for connecting to vsts.

**Comment by pabrams** [comment]
@omkar2607 Iirc, the updated instructions worked for me once I figured out how to get a Personal Access Token and get the proper collection url.

**Comment by pabrams** [comment]
I'm closing this issue since it was resolved by the merge.  Omkar, you might want to open a new one if you're having problems.
