### ISSUE TITLE
Uses blacklisted node module (gulp-tsc)

### ISSUE THREAD

**Issue by ryanmolden** [Microsoft/vsts-node-api#16]
You are using gulp-tsc, which is actually blacklisted by the gulp folks

https://github.com/kant2002/gulp-tsc/issues/8

I tried to build this repo but it gloms onto the globally installed Typescript that comes with VS, which is sadly 1.0 on my machine.

You should use gulp-typescript instead as it uses the official MS (typescript based) typescript compiler.

Sending a PR.

**Comment by bryanmacfarlane** [comment]
fixed
