### ISSUE TITLE
How do I get a list of document collections in a given TFS web extension?

### ISSUE THREAD

**Issue by pabrams** [Microsoft/vsts-node-api#160]
I just want to get the data collections in an extension so I can query them for their documents.  queryCollectionsByName returns an array of ExtensionDataCollection so I think that's the API call I want to use,  but for some reason it wants an array of ExtensionDataCollection as input - why?  And how do I create what it wants?  Is there some documentation somewhere I'm missing?  There doesn't seem to be anything useful at https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/api/vss/references/sdk_interfaces/extensiondatacollectionquery

Here's more detail; I put this question up on SO because I'm never sure whether to post questions on SO or on github:
https://stackoverflow.com/questions/49329682/how-do-i-get-a-list-of-document-collections-in-a-given-tfs-web-extension

**Comment by stephenmichaelf** [comment]
It looks like you tried passing null, did you try passing an empty array? 

I can reach out to the team who owns this service and find out the recommended query method.

**Comment by dmarcey** [comment]
@pabrams It looks like we do have a documentation gap for this API, sorry about that. We'll work to get it fixed. In the meantime, here is an example usage of the this API, from the team calendar extension:

https://github.com/Microsoft/vsts-team-calendar/blob/master/src/Calendar/EventSources/FreeFormEventsSource.ts


            **return extensionDataService.queryCollectionNames([this._teamId]).then(
                (collections: Contributions_Contracts.ExtensionDataCollection[]) => {**
                   ...
queryCollectionNames takes a list of collectionIds as its only parameter.

**Comment by dmarcey** [comment]
Actually, upon re-reading your question, it looks like I may have misinterpreted you. Are you instead looking for a list of all collections? If so, then that API does unfortunately does not exist.

**Comment by dmarcey** [comment]
If you're trying to store some data hierarchically, you could have a well-known collection, that stored a list of all your other collections, right?

**Comment by pabrams** [comment]
@dmarcey Oh, I think I see the problem.  When extensionDataService.createDocument is called, it passes a 'collectionName', I guess this is where the collection gets created if it doesn't already exist?  I was assuming that a collection name always has to be the same as the 'team ID', but I guess I can pass any collection name I want to createDocument(collectionName, document) and it will simply create the collection if a collection with that name does not already exist for the current publisher/extension?

**Comment by dmarcey** [comment]
@pabrams Yep, that's correct.

"If the collection with the name and scope provided, does not yet exist, it will be created dynamically before the document itself is created."

https://docs.microsoft.com/en-us/vsts/extend/develop/data-storage#create-a-document

**Comment by pabrams** [comment]
Thanks
