### ISSUE TITLE
How to use the "location" property supplied by some resources?

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-node-api#168]
I am trying to get the changes between two builds.  I am using the **BuildApi** and am calling **getChangesBetweenBuilds**.  This is great, but in Git it can return truncated commit messages.  I understand that the **Change** type returned by **getChangesBetweenBuilds** contains a **location** property which contains the full Url to the resources.  how do I go about calling that url from the node api?

I looked at using the **getCommit** method on the **GitApi,** but it requires a **repositoryId** which is not provided to me from the previous call to **getChangesBetweenBuilds**, so this means I would have to go and look it up.

**---Edit---**

I managed to solve this by pulling the **RestClient** out of the **WebApi** class and then just using the restclient directly.

**Comment by stephenmichaelf** [comment]
@gregpakes Glad you were able to resolve it. You may run in to issues going forward given that the APIs and locations of the APIs can change. Part of the utility of this library is abstracting all of that for you.

Yes you would need to call getBuild on the BuildApi passing the buildId you already have, the response is BuildInterfaces.Build which has a repository property of type BuildRepository. On that interface there is an id.

This would be the more stable way to do what you need to do going forward. You are going to have to make api calls one way or another to get the additional data.

Going to close but please reopen if you have follow up questions!

**Comment by gregpakes** [comment]
Thanks for the response.  It does raise the question of the **location** properties though.

My thought was that these are provided to give an api the exact stability you are talking about above.  The idea that if a resource changes between api versions, it doesn't matter if you are using the location properties because they will change too.

So you're saying that the guidance is to not use the **location** properties provided by the api?
