### ISSUE TITLE
Release - Get Release with propertyFilters not working

### ISSUE THREAD

**Issue by JeffRausch** [Microsoft/vsts-node-api#182]
### Environment
OS and version: Windows 10 - 1709
vsts-node-api version: 4.1-preview.6

### Issue Description
I'm trying to filter properties returned back from the Releases - Get Release call ([Docs](https://docs.microsoft.com/en-us/rest/api/vsts/release/releases/get%20release))
I've tried to supply the field names multiple ways and nothing seems to work, I always get back the full object which is fairly large (3+MB when I save it as a text file).
I'm trying the following url, expecting to get back only the Status field but instead I'm still getting back the complete object.
`https://{ACCOUNTNAME}.vsrm.visualstudio.com/{PROJECT}/_apis/release/releases/{RELEASENUMBER}?propertyFilters=status&api-version=4.1-preview.6`

I've tried specifying the "status" property as the following with no luck:
- status
- "status"
- %22status%22
- [status]
- %5Bstatus%5D
- ["status"]
- %5B%22status%22%5D

### Expected behaviour
Expecting to get back an object with only the properties specified by the propertyFilters parameter.

### Actual behaviour
Receiving back the full object

### Steps to reproduce
1. Call the Get Release api endpoint while supplying the "propertyFilters" parameter

**Comment by stephenmichaelf** [comment]
I was able to recreate the issue, I will ask someone on the Release team to take a look. Thanks for letting us know!

**Comment by SunnyKumarR** [comment]
Hi JeffRausch, stephenmichaelf,
Thanks for reaching out. 'propertyFilters' parameter in get release api is not serving the purpose of filtering based on release object properties. 'PropertyFilters' actually filter only those properties which you have provided separately to release. The functionality you are looking for is not provided for get release currently. We will enhance the documentation as well to make it more clear.

**Comment by stephenmichaelf** [comment]
Thanks for taking a look @SunnyKumarR. Closing this as it's expected functionality.
