### ISSUE TITLE
getWorkItems AsOf Date fails

### ISSUE THREAD

**Issue by Ninido** [Microsoft/vsts-node-api#191]
### Environment
Node version: 8.9.4
Npm version: 5.6.0 
OS and version: Windows 8
vsts-node-api version: 6.5.0
typescript: 2.8.3

### Issue Description
I'm testing the vsts-node-api library with React and TypeScript and I came upon issue with getWorkItems method and Date parameter (AsOf parameter). 

When i trigger my call i get 404 back. Same call Without Date parameter works as expected.

404 call goes to following URL:
https://[URL]/tfs/DefaultCollection/_apis/wit/workItems?ids=358093%2C358094%2C358134%2C358135%2C358136&&$expand=4

The call fails because AsOf=[date] part which is missing between "&&". 

### Steps to reproduce
```
const today: Date = new Date();
const featureIds = [358093, 358094, 358134, 358135, 358136];
// create connection object ...
const workItemTrackingApi: IWorkItemTrackingApi = await connection.getWorkItemTrackingApi();
const features: WorkItem[] = await workItemTrackingApi.getWorkItems(featureIds, undefined, today, WorkItemExpand.All, undefined);
```
### Expected behaviour
https://[URL]/tfs/DefaultCollection/_apis/wit/workItems?ids=358093%2C358094%2C358134%2C358135%2C358136&asof=[DATE]&$expand=4

### Actual behaviour
https://[URL]/tfs/DefaultCollection/_apis/wit/workItems?ids=358093%2C358094%2C358134%2C358135%2C358136&&$expand=4

**Comment by stephenmichaelf** [comment]
I will take a look! Thanks for letting us know.

**Comment by Ninido** [comment]
Is there any status update for this issue? Thanks.

**Comment by stephenmichaelf** [comment]
Not yet, will try to take a look tomorrow.

**Comment by damccorm** [comment]
Pretty sure this is the same issue as here: https://github.com/Microsoft/vsts-node-api/issues/98

I submitted a PR that should fix both.
