### ISSUE TITLE
searchCriteria in GitApi are not serialized correctly

### ISSUE THREAD

**Issue by ian-craig** [Microsoft/vsts-node-api#199]
### Environment
Node version: 10.8.0
Npm version: 6.2.0
OS and version: Windows 10
vsts-node-api version: 6.5.0

### Issue Description
The `GitQueryCommitsCriteria` object is not serialized correctly when passed to `GitApi` methods (e.g. `getCommits`).

`GitQueryCommitsCriteria` can contain nested objects, but the method used to serialize the object (`VsoClient.getSerializedObject`) only looks one level deep for objects. The result request URL looks like:

`https://company.visualstudio.com/Sway/_apis/git/repositories/reponame/commits?itemVersion=%5Bobject%20Object%5D&compareVersion=%5Bobject%20Object%5D&$skip=0&$top=50`

![image](https://user-images.githubusercontent.com/2031632/43681425-375985f0-9808-11e8-99a5-649f8dfc946a.png)

### Expected behaviour
Passing search criteria using the types defined by the API should return valid results.

### Actual behaviour
Query params are ignored, so you get no results.

### Steps to reproduce
```ts
const searchCriteria = {
    itemVersion: {
        version: "branchA"
    },
    compareVersion: {
        version: "branchB"
    }
} as GitQueryCommitsCriteria;
const commits = await gitApi.getCommits("reponame", searchCriteria, ...);
```

### Workaround (in case anyone else hits this)
```ts
// Ignore types and use query params provided on the Rest API docs
// https://docs.microsoft.com/en-us/rest/api/vsts/git/commits/get%20commits?view=vsts-rest-4.1
const searchCriteria = {
    "searchCriteria.itemVersion.version": clientVersion,
    "searchCriteria.itemVersion.versionType": "tag",
    "searchCriteria.compareVersion.version": previousVersion,
    "searchCriteria.compareVersion.versionType": "tag",
} as any as GitQueryCommitsCriteria;
const commits = await gitApi.getCommits("reponame", searchCriteria , ...);
```

**Comment by klazuka** [comment]
I also ran into this bug. @ian-craig thanks for providing the workaround!

Seems like an important bug to fix.
