### ISSUE TITLE
No way to retrieve all individual members of a project

### ISSUE THREAD

**Issue by kachkaev** [Microsoft/vsts-node-api#200]
### Environment
Node version: 10.8
Npm version: yarn 1.9.2
OS and version: macos 
vsts-node-api version: 6.5.0

### Issue Description

I would like to get a full list of individual project members. This is needed to map their email addresses to VSTS account ids and later dynamically assign these ids as release approvers. There exists a method named `coreApi.getTeamMembersWithExtendedProperties()`, which looks like it can do the job, but it's not working for me as I expect. The problem is that it returns a mix of sub-teams and individuals and calling `getTeamMembersWithExtendedProperties` again to traverse those sub-teams returns undefined instead of an array. My guess is that this happens because the sub-teams I'm trying to traverse are organisation-wide, not project-specific.

As a result, I am unable to retrieve a list of all users who can access to a specific project and this looks like a missing feature.

### Expected behaviour

I expected to have access to an API method that would traverse a project team for me, i.e. expand all sub-teams and only return individual accounts with email addresses and account ids.

What is the recommended way of traversing a project team in VSTS? If it's already possible, it seems like there is either problem documentation or with typings (which suggest that there is no _traverse_ or _expand_ option in `getTeamMembersWithExtendedProperties`).

**PS:** This is a follow-up to https://github.com/Microsoft/vsts-node-api/issues/41#issuecomment-413553851

**Comment by bryanmacfarlane** [comment]
Please provide that feedback to developer community for a service change.  The node api is generated from the service and this is a feature request of the service.

**Comment by bryanmacfarlane** [comment]
https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by kachkaev** [comment]
@bryanmacfarlane I thought the API does allow this in general, it’s just Node SDK does not cover such thing.

Meanwhile, do you know of a method that would return user id by their email address? That’s what i’m after in the end when trying to get all users in a given project.

**Comment by stephenmichaelf** [comment]
@kachkaev Do you have a sample of the API call that does this that's missing from the node lib?

**Comment by kachkaev** [comment]
@stephenmichaelf I’m trying to get the [list of users](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users/list?view=azure-devops-rest-6.0) but am unable to find a corresponding method call in the SDK. 🤔
