### ISSUE TITLE
Debugging API failures is difficult because response body is discarded

### ISSUE THREAD

**Issue by iamwillbar** [Microsoft/vsts-node-api#34]
In RestClient if the call to httpClient.send fails then the response body is discarded and is unavailable to the caller which significantly hampers debugging.

For example, if you use the updateWorkItemTemplate API to update a work item and one of the field values is invalid the err object you get back from RestClient only contains a status code and no additional information. The only way to determine the actual failure is to set a breakpoint in _sendJson and examine the value of the "contents" variable (which isn't practical when debugging a production issue).

If the contents were passed to the onResult callback or attached to the err object that would help significantly.

**Comment by stephenmichaelf** [comment]
I will investigate and see if this is still an issue.

**Comment by stephenmichaelf** [comment]
@damccorm can you take a look at this?

**Comment by damccorm** [comment]
@stephenmichaelf I think that this was taken care of in https://github.com/Microsoft/typed-rest-client/commit/9a7f674a490a70a457c54ac5c62374c9b13fce5d#diff-f31e14a10c23a24a1ea5b65fa061110f

The response body is now included in the err object's 'result' field.

**Comment by damccorm** [comment]
Added tests to ensure this, reflected in this PR - https://github.com/Microsoft/typed-rest-client/pull/77
