### ISSUE TITLE
HTTPS support through proxy

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-node-api#35]
When I set the HTTP_PROXY to an HTTP URL (http://<proxy>:8888) and a request is made to an HTTPS URL (https://<instance>.visualstudio.com/DefaultCollection), the traffic is routed through the proxy but it doesn't properly initiate the connection with a CONNECT request.  This causes all requests to fail.

It looks like this is a deficiency in your [HttpClient](https://github.com/Microsoft/vso-node-api/blob/master/api/HttpClient.ts) implementation.

**Comment by bryanmacfarlane** [comment]
correct, HTTP_PROXY was added for debugging (Charles and Fiddler).  We need true proxy support.

**Comment by gregjhogan** [comment]
Are you willing to take a dependency on [https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent)? If yes, I can submit a fix.

**Comment by bryanmacfarlane** [comment]
Sure.  A PR would be great.
