### ISSUE TITLE
gulp fails due missing tsconfig.json

### ISSUE THREAD

**Issue by bfcamara** [Microsoft/vsts-node-api#37]
I am trying to contribute to this project and the gulp command fails

`Error: ENOENT: no such file or directory, open 'E:\Github\vso-node-api\tsconfig.json'`

It is missing the tsconfig.json file.

Thanks

**Comment by jeffyoung** [comment]
Hi Bruno.  Looks like this just went in.

**Comment by bryanmacfarlane** [comment]
fixed
