### ISSUE TITLE
[Question] : How can i manage tranversal vsts group ?

### ISSUE THREAD

**Issue by Zenasoft** [Microsoft/vsts-node-api#41]
All apis refer to project teams.
Is there a way to manage transversal vsts group (at defaultcollection level) like a project team ?
Especially adding or removing members.

**Comment by stephenmichaelf** [comment]
Looks like the user is no longer on GitHub, closing.

**Comment by kachkaev** [comment]
@stephenmichaelf I'm also facing a problem with traversing teams. Basically what I'd like to do is to get all human members of the given project team. `coreApi.getTeamMembersWithExtendedProperties()` returns a mix of team references and human members and I can't figure out what API call to make to expand those teams. Any suggestions?

**Comment by kachkaev** [comment]
ping @stephenmichaelf 🙂
