### ISSUE TITLE
Error when querying the release API

### ISSUE THREAD

**Issue by Jaxwood** [Microsoft/vsts-node-api#45]
I have tried to use the vsts-node-api to create a new release definition. However I always get the same response: 

> Error: Failed to find api location for area: Release id: d8f96f24-8ea7-4cb6-baab-2df8fc515665 statusCode undefined.

The api endpoint I'm targeting is [createReleaseDefinition](https://github.com/Microsoft/vsts-node-api/blob/master/api/ReleaseApi.ts#L1408) using the promise interface.

I've succesfully used the BuildApi and was able to create a build definition using this API.

**Comment by bryanmacfarlane** [comment]
Were you connecting to VSTS or an on-prem version?

**Comment by Jaxwood** [comment]
@bryanmacfarlane I was connection to VSTS. I used a personal access token with all scopes allowed.

**Comment by chandan-anjani** [comment]
Can you please share your code snippet? 

And I hope you are using url with 'vsrm' e.g. https://{your tenant name}.vsrm.visualstudio.com/DefaultCollection.  You may take a look into https://blogs.msdn.microsoft.com/chandananjani/2016/04/27/using-releasehttpclient-for-interacting-with-releasemanagement-service/ as well.
