### ISSUE TITLE
vso-node-api 5.0.0: node cannot find module

### ISSUE THREAD

**Issue by zumwald** [Microsoft/vsts-node-api#54]
package.json declares WebApi.js in the root of the package, but it's not there. The package seems to contain a copy of the source, rather than the javascript in a npm-consumable structure.

**Comment by bryanmacfarlane** [comment]
Yes.  That was fixed 5 drops ago.  If you do npm install vso-node-api you get 5.0.5

**Comment by zumwald** [comment]
5.0.5 suffers from a similar issue: package.json defines main as "./_build/WebApi.js" but there's no _build directory in the package. Instead all of the /api files exist in both .js & .ts form at the root of the package.

**Comment by zumwald** [comment]
workaround of course is to require('vso-node-api/WebApi') - but kind of a time sink to have require broken by newer versions.

**Comment by bryanmacfarlane** [comment]
no it doesn't have the same issue.  See that one is source and one is built code

$ npm install vso-node-api@5.0.0


...
$ ls -la vso-node-api
total 72
drwxr-xr-x  16 bryan  staff   544 Sep 16 16:09 .
drwxr-xr-x   6 bryan  staff   204 Sep 16 16:09 ..
-rw-r--r--   1 bryan  staff   636 Aug 31 15:37 .npmignore
-rw-r--r--   1 bryan  staff  3051 Jul 23 18:46 CONTRIBUTING.md
-rw-r--r--   1 bryan  staff  1164 Jul 23 18:46 LICENSE
-rw-r--r--   1 bryan  staff  2779 Aug 31 15:37 README.md
-rw-r--r--   1 bryan  staff  3197 Jul 23 18:46 ThirdPartyNotices.txt
drwxr-xr-x  28 bryan  staff   952 Sep 16 16:09 api
drwxr-xr-x   3 bryan  staff   102 Aug 31 15:37 dependencies
drwxr-xr-x   3 bryan  staff   102 Aug 31 15:37 docs
-rw-r--r--   1 bryan  staff  1398 Aug 31 15:37 make.js
-rw-r--r--   1 bryan  staff  2709 Sep 16 16:09 package.json
drwxr-xr-x  10 bryan  staff   340 Sep 16 16:09 samples
-rw-r--r--   1 bryan  staff   229 Sep  2 10:30 tsconfig.json
drwxr-xr-x   5 bryan  staff   170 Sep 16 16:09 typings
-rw-r--r--   1 bryan  staff   371 Aug 31 15:37 typings.json

$ npm install vso-node-api@5.0.5

$ ls -la vso-node-api
total 2320
drwxr-xr-x  53 bryan  staff    1802 Sep 16 16:10 .
drwxr-xr-x   6 bryan  staff     204 Sep 16 16:10 ..
-rw-r--r--   1 bryan  staff   24140 Sep  2 14:54 BuildApi.d.ts
-rw-r--r--   1 bryan  staff   74888 Sep  2 14:54 BuildApi.js
...
-rw-r--r--   1 bryan  staff    2814 Sep  2 14:54 VsoClient.d.ts
-rw-r--r--   1 bryan  staff   12307 Sep  2 14:54 VsoClient.js
-rw-r--r--   1 bryan  staff    3676 Sep  2 14:54 WebApi.d.ts
-rw-r--r--   1 bryan  staff    6978 Sep  2 14:54 WebApi.js

**Comment by bryanmacfarlane** [comment]
Changes in the require patterns should have been across major versions and the samples show the usage:
https://github.com/Microsoft/vsts-node-api/tree/master/samples

**Comment by bryanmacfarlane** [comment]
Let me look at the package.json issue you're referring to however.

**Comment by amanimariem** [comment]
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/vso-node-api !

**Comment by stephenmichaelf** [comment]
@zumwald Is this still an issue? :)

@amanimariem Could you provide some more details?

**Comment by stephenmichaelf** [comment]
Please reopen and add additional details if this is still an issue.
