### ISSUE TITLE
Version without typescript

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/vsts-node-api#56]
The project I am working on does not use typescript. Is there a version of this code that is not in typescript?

**Comment by bryanmacfarlane** [comment]
The code compiles to javascript.  The compiled output is what you're looking for.  The actual npm module you consume is just javascript.

**Comment by bryanmacfarlane** [comment]
... so there's no requirement that consumers of this use typescript.  It's just written in typescript.

**Comment by jrock2004** [comment]
So when I try to include `var vm = require('vso-node-api')` and I run my project it tells me the module does not exist. Was thinking because when I look at the directory in bower_components all I see is TS files

**Comment by bryanmacfarlane** [comment]
See the samples.  Not sure about bower, our samples use node as the loader.
