### ISSUE TITLE
TF401349 error occurs when create work item.

### ISSUE THREAD

**Issue by EddieCCCCC** [Microsoft/vsts-node-api#60]
TF401349 error occurs when use this API to create work item on On-premise TFS, it works correctly on VSTS. Does this API support On-premise TFS?

**Comment by stephenmichaelf** [comment]
@EddieCCCCC Yes this supports on prem, are you still having issues? What version of TFS?

**Comment by stephenmichaelf** [comment]
Closing, please reopen if it's still an issue.
