### ISSUE TITLE
Work item creation issue in TFS 2015.2

### ISSUE THREAD

**Issue by ranuka2** [Microsoft/vsts-node-api#62]
I'm getting following error when creating bug item in TFS 2015.2 (On permise) via vso-node-api package, however the same code is working perfectly in my VSTS (online) subscription.

[Error: Failed Request: Bad Request(400) - TF401349: An unexpected error has occurred, please verify your request and try again.] statusCode: 400

I'm using the WorkItemTrackingApi/createWorkItem function in vso-node-api library to create the work item.

I have raised following stackoveflaw thread with further info,

http://stackoverflow.com/questions/40147345/work-item-creation-issue-in-tfs-2015-2-with-vsts-node-api

**Comment by ranuka2** [comment]
Any update on this issue please?

**Comment by DSakura1987** [comment]
I don't think TFS on permise supports access token - this [post](https://social.msdn.microsoft.com/Forums/vstudio/en-US/dfc9da69-dc6c-4307-98bb-35b08beee512/onprem-tfs-2015-rest-api-with-oauth?forum=tfsgeneral) points out only NTLM and Kerberos supported.

**Comment by bryanmacfarlane** [comment]
That doesn't sound like an authentication issue,  it would be a 401, not a 400 / bad request.

**Comment by saakshyee** [comment]
While customising the WIT using VSTS layout, I faced the error as TF401349. The field is created but displayed on the layout. Pls suggest

**Comment by BetaVersionAnurag** [comment]
I am also facing the same issue, we have added a new user to TFS. when He tries to run any work item query he is getting the below error-
TF401349: An unexpected error has occurred, please verify your request.

**Comment by stephenmichaelf** [comment]
@BetaVersionAnurag What version of TFS are you using? I will take a look.

**Comment by stephenmichaelf** [comment]
Closing, please reopen if it's still an issue.
