### ISSUE TITLE
Issue in getClassificationNode function

### ISSUE THREAD

**Issue by ranuka2** [Microsoft/vsts-node-api#67]
I'm getting following error when using getClassificationNode() function

[Error: Failed Request: Bad Request(400) - https://xxxxx.visualstudio.com/MyFirstProject/_apis/wit/classificationNodes/MyFirstProjectArea1Test] statusCode: 400

Following is the code sample,
var areaPath = "MyFirstProject\Area1Test";
this.vstsWI.getClassificationNode(this.projName, wi.TreeStructureGroup.Areas, areaPath).then((nodex: wi.WorkItemClassificationNode) => {
console.log(nodex);
}).catch((e) => {
console.error(e);
});

**Comment by dakale** [comment]
I was able to recreate this. 

400 response was received when `areaPath` was invalid. The project name (root of area paths) cannot be included in the area path, ie you should use `areaPath = 'Area1Test'` instead. Additionally if the paths are nested further, the proper path separator would be `/` not `\` (which will escape the JS string.)

If this is still an issue please open a new issue. @stephenmichaelf I recommend closing this at this time for being inactive/not a bug

**Comment by stephenmichaelf** [comment]
Thanks @dakale.

@ranuka2 Please follow the recommendation and reopen if you are still stuck.
