### ISSUE TITLE
Always getting wrong version of api when using the build api

### ISSUE THREAD

**Issue by Yannike** [Microsoft/vsts-node-api#68]
I am trying to access build info from a TFS 2017 server. When I call the getBuilds functions the following:

`this.vsoClient.getVersioningData("3.0-preview.3", "build", "0cd358e1-9217-4d94-8269-1c1ee6f93dcf", routeValues, queryValues)`

always return 3.0-preview.3, and that doesn't return any build. If I change the apiVersion to the hardcoded 2.0 value ( the latest build api version), I get the builds I was expecting.

I haven't touch this code for a while, and I am pretty sure it used to work with TFS 2015.2 server.

**Comment by stephenmichaelf** [comment]
@Yannike Are you still having issues?

**Comment by stephenmichaelf** [comment]
Closing, please reopen if it's still an issue.
