### ISSUE TITLE
VSTS work item creation throttling issue

### ISSUE THREAD

**Issue by ranuka2** [Microsoft/vsts-node-api#71]
I’m developing a VSTS extension with a build task which should create up to 20,000 work items in a single build. Work items are created using WorkItemTrackingApi/createWorkItem function of vsts-node-api package. In current implementation, extension sends a request to create each work item, VSTS starts to throttling after creating about 100 work items. 

Following are the two errors logged in the build console.

• (2017-01-08T12:35:13.1385597Z Error: connect ETIMEDOUT 11.11.111:111:111)

• 2017-01-08T12:36:45.0090704Z Error: Failed Request: Internal Server Error(500) - TF246020: Microsoft SQL Server encountered an error while processing the results from one of the Team Foundation Server databases. The error may be caused by insufficient resources on the server. Wait a few minutes and try the operation again. If the problem persists, contact a SQL Server administrator. 2017-01-08T12:36:45.0090704Z ThrottlingMode = Unknown, MildResourceType = None, SignificantResourceType = None

**Comment by bryanmacfarlane** [comment]
That's not a node api issue, that's the service/server returning that.
