### ISSUE TITLE
HttpClient is assuming json

### ISSUE THREAD

**Issue by bryceg** [Microsoft/vsts-node-api#78]
HttpClient should not assume the content type of the body by forcing a JSON.stringify

```javascript
if (objs) {
            reqData = JSON.stringify(objs, null, 2);
            options.headers["Content-Length"] = Buffer.byteLength(reqData, 'utf8');
        }
```

Let the user serialize the body themselves, or provide an option to not stringify the content.  Unable to use this to perform my oauth2 request due to my x-www-form-urlencoded content being corrupted by the json stringify.

**Comment by bryanmacfarlane** [comment]
The http client in this package is deprecated and the api no longer uses it.  It now uses

https://github.com/Microsoft/typed-rest-client

and the http client in that package does not force json.  The rest client does.
