### ISSUE TITLE
Release API doesn't work against vsts but does against on prem

### ISSUE THREAD

**Issue by jabbera** [Microsoft/vsts-node-api#85]
Version: 5.1.2

Repro code:

        let token: string = tl.getEndpointAuthorizationParameter("SystemVssConnection", "AccessToken", false);
        let collectionUrl: string = tl.getEndpointUrl("SystemVssConnection", false);
        let authHandler = vsts.getPersonalAccessTokenHandler(token);
        let connect = new vsts.WebApi(collectionUrl, authHandler);
        let releaseApi: ra.IReleaseApi = connect.getReleaseApi();

        await releaseApi.getReleases(this.teamProject);

I get the error: Error: Failed to find api location for area: Release id: a166fde7-27ad-408e-ba75-703c2cc9d500

other apis work fine. What am I doing wrong?

**Comment by jabbera** [comment]
needed vsrm in the url

**Comment by stephenmichaelf** [comment]
That was a workaround, we are working on a more convenient resolution where you don't need to do that (in case URLs change in the future).

**Comment by stephenmichaelf** [comment]
This was resolved by #139.
