### ISSUE TITLE
getCommitsBatch doesn't return remoteUrl when using only ids

### ISSUE THREAD

**Issue by jabbera** [Microsoft/vsts-node-api#86]
The little says it all. 

let blah: giti.GitQueryCommitsCriteria = { ids = ["A", "B"] } as git.GitQueryCommitsCriteria
await api.getCommitsBatch(blah, restofargs)

no remoteurl returned:-(

**Comment by stephenmichaelf** [comment]
@jabbera I tried to recreate the issue with the latest on master (6.3.0-preview) and the code is working as expected for me. Here is what I did:

```
const gitApi: IGitApi = await vsts.getGitApi();
const commitCriteria: GitQueryCommitsCriteria = { ids: ["a---8", "6---b"] } as GitQueryCommitsCriteria;
const respositoryId: string = "b---b";
const commitsBatch: GitCommitRef[] = await gitApi.getCommitsBatch(commitCriteria, respositoryId);

if (commitsBatch) {
    for (var commitBatch of commitsBatch) {
        console.log("url: " + commitBatch.url);
    }
}
```

Are you still having this issue? If so could you add some more details. Thanks!

**Comment by stephenmichaelf** [comment]
Closing since this seems to be working, please reopen and add additional details if you are still having issues.
