### ISSUE TITLE
Generated API interfaces should include /* doc comments

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/vsts-node-api#89]
For TypeScript developers that do something like this:

```
let vstsBuild: ba.IBuildApi = connection.getBuildApi();
```

Intelli-sense should work, but doesn't because the generated interfaces are missing doc comments. These comments are included on the classes that implement the API interfaces.

**Comment by japj** [comment]
Is the interface generation implemented/described somewhere publicly? (In case someone outside Microsoft would want to fix this?)

**Comment by stephenmichaelf** [comment]
Interfaces now have doc comments and intellisense is working.
