### ISSUE TITLE
401 while getting build definitions or builds

### ISSUE THREAD

**Issue by kksevta** [Microsoft/vsts-node-api#97]
For one of the TFS server, I am getting 401 during getting builds
But for other TFS its working. I am having same level of access for both servers.
One server is running on https(401) and other is on http(working)
Both TFS are having different domains
What could be the possible reason for that?

**Comment by stephenmichaelf** [comment]
@kksevta Are you still having this issue? Could you post some more details about how you are making the calls? Are you able to make a raw HTTP request over SSL to the server?

**Comment by stephenmichaelf** [comment]
Closing for now, please reopen with additional details if you are still having issues.
